#ifndef __INC_SERVICE_H__
#define __INC_SERVICE_H__

/*** General Macros ***/
#define ENABLE_DEFAULT_PRIV//Oyun içi dropları(item, yang, exp) varsayılan olarak etkinleştirir (common -> priv_settings)
/*** General Macros ***/

#define _IMPROVED_PACKET_ENCRYPTION_//YMİR PACKET ŞİFRELEME
//#define __AUCTION__
#define ENABLE_WON_EXCHANGE//Won_Yang_Çevirme_Sistemi
#define ENABLE_YMIR_EXP_BONUS_EDIT//EXP BONUS DÜZENLEMESİ
#define DISABLE_YANG_BOMB//YANG BOMBASI FİX
#define KYGN_ITEM_REMOVE_OR_SELL//HIZLI SİLME VE SATMA SİSTEMİ
#define __SKILL_COLOR_SYSTEM__//RENKLİ SKİLL SİSTEMİ(BECERİ BOYAMA)
#define ENABLE_KOSTUMPARLA//KOSTÜM EFEKT VERME TAŞI SİSTEMİ
#define _ITEM_SHOP_SYSTEM//OYUN İÇİ RENDER TARGETLİ NESNE MARKET SİSTEMİ
#define ENABLE_TURN_BACK_SYSTEM//ZİNDANLARA GERİ DÖNÜŞ SİSTEMİ
#define ELEMENT_TARGET//ELEMENT TARGET
#define ENABLE_PORT_SECURITY//PORT KORUMASI
#define __PET_SYSTEM__//PET SİSTEMİ
#define __UDP_BLOCK__//UDB ENGELLEME
#define __WOLFMAN_CHARACTER__//WOLFMAN GÜNCELLEMESİ
#define NEW_COSTUME_SOCKET_RING
#define ENABLE_WOLFMAN_CHARACTER//WOLFMAN GÜNCELLEMESİ
#define ENABLE_CHEQUE_SYSTEM//WON SİSTEMİ
#define ENABLE_OFFLINE_SHOP_SYSTEM//
#define ENABLE_PRIVATESHOP_SEARCH_SYSTEM//TİCARET CAMI SİSTEMİ
	#define ITEM_SET_BONUS
#define ENABLE_SPECIAL_STORAGE//EK ENVANTER (K) SİSTEMİ
#define ENABLE_NEW_AFFECT_POTION//YENİ EFFECT
#define __WEAPON_COSTUME_SYSTEM__//SİLAH KOSTÜM SİSTEMİ
#define ENABLE_EXTENDED_ITEMNAME_ON_GROUND//
#define __NEW_ARROW_SYSTEM__//OK ÇANTASI SİSTEMİ
#define WJ_SECURITY_SYSTEM//GİRİŞ GÜVENLİK ŞİFRESİ SİSTEMİ
#define ENABLE_YMIR_AFFECT_FIX//YMİR AFFECT DÜZENLEMESİ
#define BINDSYSTEM_WITH_PASSWORD//
#define __COSTUME_ATTR_SYSTEM__//KOSTÜM EFSUNLAMA SİSTEMİ
#define __SEND_TARGET_INFO__//MOB BİLGİ SİSTEMİ
#define __OFFLINE_SHOP_FIX_OPEN	//
#define __OFFLINE_SHOP_VALUE_MAX 2000000000//
#define __OFFLINE_SHOP_WARNING "[Protect Offline] Have more than 2.000.000.000 Yang!"//
#define ENABLE_CUBE_RENEWAL//2021 YENİ NESİL CUBE SİSTEMİ
#define ENABLE_CUBE_ATTR_SOCKET//CUBE (ARINDIRMA)EFSUN
#define ENABLE_DS_GRADE_MYTH//MİTSİ SİMYA GÜNCELLEMESİ
#if defined(ENABLE_DS_GRADE_MYTH)
#define ENABLE_DS_GRADE_EPIC//DESTANSI SİMYA
#endif
#define __FULL_NOTICE_SYSTEM__//GM NOTİCE KONUŞMASI
#define RELOAD_SHOP//GENİŞLETİLMİŞ RELOAD KOMUTLARI
#define PRICE_TYPE//NPC İTEM TAKAS SİSTEMİ
#define ENABLE_IGNORE_LOWER_BUFFS//DÜŞÜK BUFF ENGELLEME SİSTEMİ
#define __SASH_SYSTEM__//OFFİCAL KUŞAK SİSTEMİ
#define ENABLE_SHOW_CHEST_DROP//SANDIK AYNASI SİSTEMİ
#define ENABLE_NEW_PET_SYSTEM//YENİ NESİL OFFİCAL EVRİMLİ LEVELLİ PET SİSTEMİ
#define ENABLE_PET_ATTR_DETERMINE//PET EFSUNLAMA SİSTEMİ
#define ADD_NEW_BONUS//YENİ BONUSLAR
#define WJ_MAGIC_REDUCION_BONUS//
#define __7AND8TH_SKILLS__//OFFİCAL 7. VE 8. SKİLLER
#define ENABLE_AFFECT_POLYMORPH_REMOVE//DÖNÜŞÜM SİLME SİSTEMİ
#define ENABLE_BATTLE_PASS//BATTLEPASS SİSTEMİ
#define ENABLE_REBIRT_SYSTEM//REBİRTH SİSTEMİ
#define __EXTENDED_ITEM_COUNT__//30K İTEM STACK SİSTEMİ
#define ENABLE_GUVENLI_PC//GÜNVELİ BİLGİSAYAR SİSTEMİ
#define ENABLE_AURA_SYSTEM//OFFİCAL AURA KUŞAĞI SİSTEMİ
#define ENABLE_BEVIS_BOSS_TRACKING_SYSTEM//BOSS TAKİP SİSTEMİ
#define ENABLE_GAYA_SYSTEM//GAYA SİSTEMİ
#define ENABLE_TITLE_SYSTEM//ÜNVAN SİSTEMİ
#define ENABLE_SWITCHBOT//YENİ SERVER TARAFLI EFSUN BOTU 
#define __DS_SET__//SİMYA SET BONUS SİSTEMİ
#define ENABLE_EXTENDED_DS_INVENTORY//YENİ EK SİMYA ENVANTERİ
#define __VIEW_TARGET_DECIMAL_HP__//HP TARGET GÖRÜNTÜ DÜZENLEMESİ
#define LWT_BUFFI_SYSTEM//YARDIMCI BUFFİ ŞAMAN SİSTEMİ
#define ENABLE_COSTUME_HIDE_SYSTEM//KOSTÜM_GİZLEME-GÖSTER_SİSTEMİ
#define OTOMATIK_AV//OTO_AV_METİN_VE_SLOT_BOTU
#define ENABLE_REMOTE_SHOP//UZAKTAN MARKET SISTEMI
#define ENABLE_MESSENGER_BLOCK//////OFFİCAL ENGELLEME SİSTEMİ
#define __NEW_EXCHANGE_WINDOW__////OFFİCAL YENİ TİCARET PENCERESİ
#define ENABLE_AFFECT_BUFF_REMOVE///SKİLL SİLME SİSTEMİ
#define ENABLE_GLOVE_SYSTEM
#define ENABLE_NEW_LOGIN_LEVEL//CONFIG KARAKTER BAŞLANGIÇ LEVEL
#define ENABLE_STONE_DEDECT_RENEWAL//METİNE IŞINLANMA DEDEKTÖRÜ
#define __LEADER_ON_GUILD__///LONCA LIDERI EFEKTI
#define ITEM_CHECKINOUT_UPDATE///SAĞ TIK DEPO/ENVANTER İTEM EKLEME VE ÇIKARMA
#define ENABLE_PM_ALL_SEND_SYSTEM///YÖNETİCİ TOPLU MESAJ PANELİ
#define ENABLE_KILL_STATISTICS
//#define URIEL_ANTI_CHEAT
#define __CHATTING_WINDOW_RENEWAL__//Tr sohbet penceresi güncellemesi
#define ENABLE_DICE_SYSTEM//Grup zar sistemi
#define __VERSION_162__
#ifdef __VERSION_162__
	#define HEALING_SKILL_VNUM 265
#endif
#endif
//OFFLINESHOP
#define __ENABLE_NEW_OFFLINESHOP__//LİSANSLI **"ORJİNAL"** İKARİUS GLOBAL OFFLİNE SHOP(İKARİUSTAN ALINMA VAREZDEKİ NEYDİĞİ BELİRSİZ SİSTEM DEĞİL)
#define ENABLE_NEW_OFFLINESHOP_LOGS//LİSANSLI **"ORJİNAL"** İKARİUS GLOBAL OFFLİNE SHOP(İKARİUSTAN ALINMA VAREZDEKİ NEYDİĞİ BELİRSİZ SİSTEM DEĞİL)
#ifdef __ENABLE_NEW_OFFLINESHOP__//LİSANSLI **"ORJİNAL"** İKARİUS GLOBAL OFFLİNE SHOP(İKARİUSTAN ALINMA VAREZDEKİ NEYDİĞİ BELİRSİZ SİSTEM DEĞİL)
#define ENABLE_NEW_SHOP_IN_CITIES//LİSANSLI **"ORJİNAL"** İKARİUS GLOBAL OFFLİNE SHOP(İKARİUSTAN ALINMA VAREZDEKİ NEYDİĞİ BELİRSİZ SİSTEM DEĞİL)
#define __ENABLE_CHEQUE_SYSTEM__//
#endif
#define __ENABLE_LARGE_DYNAMIC_PACKET__//İKARİUS OFFLİNE SHOP DİNAMİK GENİŞLEME PAKET
#ifdef ENABLE_OFFLINESHOP_DEBUG
#	ifdef __WIN32__
#		define OFFSHOP_DEBUG(fmt , ...) sys_log(0,"%s:%d >> " fmt , __FUNCTION__ , __LINE__, __VA_ARGS__)
#	else
#		define OFFSHOP_DEBUG(fmt , args...) sys_log(0,"%s:%d >> " fmt , __FUNCTION__ , __LINE__, ##args)
#	endif
#else
#	define OFFSHOP_DEBUG(...)   
#endif

	#define YANG_LIMIT
	#ifdef YANG_LIMIT
		typedef long long LDWORD;
		typedef unsigned long long ULDWORD;
	#endif

