#ifndef __INC_METIN_II_DB_QID_H__
#define __INC_METIN_II_DB_QID_H__
#define __SKILL_COLOR_SYSTEM__
/**
 * @version	05/06/10 Bang2ni - 아이템 가격정보 쿼리 추가(QID_ITEMPRICE_XXX)
 */
enum QID
{
    QID_PLAYER,				// 0
    QID_ITEM,				// 1
    QID_QUEST,				// 2
    QID_AFFECT,				// 3
    QID_LOGIN,				// 4
    QID_SAFEBOX_LOAD,			// 5
    QID_SAFEBOX_CHANGE_SIZE,		// 6
    QID_SAFEBOX_CHANGE_PASSWORD,	// 7
    QID_SAFEBOX_CHANGE_PASSWORD_SECOND,	// 8
    QID_SAFEBOX_SAVE,			// 9
    QID_ITEM_SAVE,			// 10
    QID_ITEM_DESTROY,			// 11
    QID_QUEST_SAVE,			// 12
    QID_PLAYER_SAVE,			// 13
    QID_HIGHSCORE_REGISTER,		// 14
    QID_PLAYER_DELETE,			// 15
    QID_LOGIN_BY_KEY,			// 16
    QID_PLAYER_INDEX_CREATE,		// 17
    QID_ITEM_AWARD_LOAD,		// 18
    QID_ITEM_AWARD_TAKEN,		// 19
    QID_GUILD_RANKING,			// 20

	// MYSHOP_PRICE_LIST
    QID_ITEMPRICE_SAVE,			///< 21, 아이템 가격정보 저장 쿼리
    QID_ITEMPRICE_DESTROY,		///< 22, 아이템 가격정보 삭제 쿼리
    QID_ITEMPRICE_LOAD_FOR_UPDATE,	///< 23, 가격정보 업데이트를 위한 아이템 가격정보 로드 쿼리
    QID_ITEMPRICE_LOAD,			///< 24, 아이템 가격정보 로드 쿼리
#ifdef __SKILL_COLOR_SYSTEM__
	QID_SKILL_COLOR,
	QID_SKILL_COLOR_SAVE,
#endif
#ifdef __ENABLE_NEW_OFFLINESHOP__
	QID_OFFLINESHOP_ADD_ITEM,
	QID_OFFLINESHOP_EDIT_ITEM,
	QID_OFFLINESHOP_DELETE_SHOP,
	QID_OFFLINESHOP_DELETE_SHOP_ITEM,
	QID_OFFLINESHOP_REMOVE_ITEM,
	QID_OFFLINESHOP_UPDATE_SOLD_ITEM,

	QID_OFFLINESHOP_CREATE_SHOP,
	QID_OFFLINESHOP_CREATE_SHOP_ADD_ITEM,
	QID_OFFLINESHOP_SHOP_CHANGE_NAME,
	QID_OFFLINESHOP_SHOP_UPDATE_DURATION,

	QID_OFFLINESHOP_SAFEBOX_DELETE_ITEM,
	QID_OFFLINESHOP_SAFEBOX_ADD_ITEM,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_INSERT_VALUTES,
	QID_OFFLINESHOP_SAFEBOX_UPDATE_VALUTES_ADDING,

	QID_OFFLINESHOP_OFFER_ADD,
	QID_OFFLINESHOP_OFFER_UPDATE_NOTIFIED,
	QID_OFFLINESHOP_OFFER_UPDATE_ACCEPTED,
	QID_OFFLINESHOP_OFFER_DELETE,
	QID_OFFLINESHOP_OFFER_DELETE_BY_SHOP,

	//AUCTION
	QID_OFFLINESHOP_AUCTION_INSERT,
	QID_OFFLINESHOP_AUCTION_INSERT_OFFER,
	QID_OFFLINESHOP_AUCTION_DELETE,
	QID_OFFLINESHOP_AUCTION_DELETE_OFFERS,
	QID_OFFLINESHOP_AUCTION_UPDATE_DURATION,
#endif
	// END_OF_MYSHOP_PRICE_LIST
};

#endif
